"""
Django settings for did project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# ==============================
# 📁 المسارات الأساسية للمشروع
# ==============================
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================
# 🔐 إعدادات الأمان
# ==============================
SECRET_KEY = 'django-insecure-)koi1nuvzh87osxx&u)t&@y&l_a63t$eef)+jr!l!c7nyy9&s-'
DEBUG = True
ALLOWED_HOSTS = []


# ==============================
# 📦 التطبيقات المثبتة
# ==============================
INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'core',
    'store',
    'orders',
]

# تفعيل نموذج المستخدم المخصص
AUTH_USER_MODEL = 'core.User'


# ==============================
# ⚙️ إعدادات الوسطاء (Middleware)
# ==============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==============================
# 🌐 روابط النظام
# ==============================
ROOT_URLCONF = 'did.urls'


# ==============================
# 🧩 إعداد القوالب (Templates)
# ==============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # تعريف مجلد القوالب العام
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==============================
# 🚀 إعداد WSGI
# ==============================
WSGI_APPLICATION = 'did.wsgi.application'


# ==============================
# 🗄️ قاعدة البيانات
# ==============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==============================
# 🔐 التحقق من كلمات المرور
# ==============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================
# 🌍 الإعدادات الدولية
# ==============================
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_TZ = True


# ==============================
# 🖼️ إعداد الملفات الثابتة والإعلامية
# ==============================
# ملفات CSS / JS / الصور الثابتة
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # ملفات التطوير المحلية
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # مجلد تجميع الملفات النهائية

# الملفات المرفوعة من المستخدمين (صور - ملفات)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# ==============================
# 🆔 الإعداد الافتراضي للمفاتيح الأساسية
# ==============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
